server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_utils?useSSL=false
    username: gerrymc
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
